version: '3.4'

services:
  ravi.learn.docker.web:
    image: ${DOCKER_REGISTRY-}ravilearndockerweb
    build:
      context: .
      dockerfile: ravi.learn.docker.web/Dockerfile
    environment:
     - DB_Server
     - DB_UserId
     - DB_Pwd