// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ravi.learn.docker.web.Data;

namespace ravi.learn.docker.web.Migrations
{
    [DbContext(typeof(MagContext))]
    [Migration("20190502095916_initSqlAz")]
    partial class initSqlAz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ravi.learn.docker.web.Models.Magazine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Magazine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MSDN Magazine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Docker Magazine"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EF Core Magazine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
